const drugsInformationRoute = require("./drugs_informations/routes/drugs_informations.route");
const interactionNamesRoute = require("./drugs_informations/routes/interaction_names.route");
const interactionsRoute = require("./interactions/routes/interactions.route");
const tutorialStepsRoute = require("./tutorial_steps/routes/tutorial_steps.route");
const authenticationRoute = require("./auth/routes/authentication.route");
const usersRoute = require("./auth/routes/users.route");
const storeRoute = require("./store/routes/store_items.route");
const drugsReviewsRoute = require("./drugs_reviews/routes/drugs_reviews.route");
const homeRoute = require("./home/routes/home.route");
const express = require("express");
const api = express.Router();

api.use("/drugs-information", drugsInformationRoute);
api.use("/interaction-names", interactionNamesRoute);
api.use("/interactions", interactionsRoute);
api.use("/tutorial-steps", tutorialStepsRoute);
api.use("/auth", authenticationRoute);
api.use("/users", usersRoute);
api.use("/store", storeRoute);
api.use("/drugs-reviews", drugsReviewsRoute);
api.use("/home", homeRoute);
module.exports = api;
