import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import theme from "@/utils/theme/theme";
import { ThemeProvider } from "@mui/material/styles";
import { Inter } from "next/font/google";
import StoreProvider from "./StoreProvider";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
// const geistSans = localFont({
// 	src: "./fonts/GeistVF.woff",
// 	variable: "--font-geist-sans",
// 	weight: "100 900",
// });
// const geistMono = localFont({
// 	src: "./fonts/GeistMonoVF.woff",
// 	variable: "--font-geist-mono",
// 	weight: "100 900",
// });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<AppRouterCacheProvider>
					<StoreProvider>
						<ThemeProvider theme={theme}>{children}</ThemeProvider>
					</StoreProvider>
				</AppRouterCacheProvider>
			</body>
		</html>
	);
}
